const firstnames = [
    'Ben',
    'Jonas',
    'Leon',
    'Paul',
    'Finn / Fynn',
    'Noah',
    'Elias',
    'Luis / Louis',
    'Felix',
    'Lukas / Lucas',
    'Henry / Henri',
    'Maximilian',
    'Luca / Luka',
    'Oskar / Oscar',
    'Emil',
    'Anton',
    'Max',
    'Theo',
    'Jakob / Jacob',
    'Matteo',
    'Liam',
    'Moritz',
    'Julian',
    'Leo',
    'David',
    'Alexander',
    'Milan',
    'Philipp',
    'Niklas / Niclas',
    'Carl / Karl',
    'Tim',
    'Samuel',
    'Mats / Mads',
    'Tom',
    'Leonard',
    'Erik / Eric',
    'Jonathan',
    'Hannes',
    'Rafael / Raphael',
    'Linus',
    'Jan',
    'Jona / Jonah',
    'Fabian',
    'Vincent',
    'Lennard / Lennart',
    'Mika',
    'Adrian',
    'Till',
    'Simon',
    'Jannik / Yannik / Yannick',
    'Aaron',
    'Johann',
    'Nico / Niko',
    'Valentin',
    'Benjamin',
    'Levi',
    'Julius',
    'Joshua',
    'Maxim / Maksim',
    'Johannes',
    'Marlon',
    'Constantin / Konstantin',
    'Jannis / Janis / Yannis',
    'Mattis / Mathis / Matthis',
    'Luke / Luc',
    'Lenny / Lenni',
    'Florian',
    'Phil',
    'Nick',
    'Daniel',
    'Benedikt',
    'Mohammed / Muhammad',
    'Toni / Tony',
    'Nils / Niels',
    'Kilian',
    'Ole',
    'Theodor',
    'Milo / Milow',
    'Sebastian',
    'Lian',
    'Malte',
    'Dominic / Dominik',
    'Tobias',
    'Timo',
    'John',
    'Artur / Arthur',
    'Lennox',
    'Gabriel',
    'Lias',
    'Adam',
    'Lasse',
    'Lio',
    'Joris',
    'Levin',
    'Noel',
    'Pepe',
    'Fritz',
    'Justus',
    'Jayden / Jaden',
    'Michael',
    'Emma',
    'Hannah / Hanna',
    'Mia',
    'Sofia / Sophia',
    'Emilia',
    'Lina',
    'Anna',
    'Marie',
    'Mila',
    'Lea / Leah',
    'Leni',
    'Clara / Klara',
    'Lena',
    'Luisa / Louisa',
    'Leonie',
    'Amelie',
    'Emily / Emilie',
    'Johanna',
    'Ella',
    'Nele / Neele',
    'Sophie / Sofie',
    'Charlotte',
    'Ida',
    'Lilly / Lilli',
    'Laura',
    'Maja / Maya',
    'Mathilda / Matilda',
    'Lara',
    'Frieda / Frida',
    'Lia / Liah / Lya',
    'Greta',
    'Lotta',
    'Sarah / Sara',
    'Melina',
    'Paula',
    'Julia',
    'Marlene',
    'Pia',
    'Alina',
    'Nora',
    'Elisa',
    'Victoria / Viktoria',
    'Mira',
    'Lisa',
    'Isabella',
    'Anni',
    'Juna / Yuna',
    'Isabell / Isabel / Isabelle',
    'Zoe / Zoé',
    'Mara / Marah',
    'Luna',
    'Luise / Louise',
    'Finja / Finnja',
    'Maria',
    'Josephine/ Josefine',
    'Pauline',
    'Romy',
    'Theresa / Teresa',
    'Merle',
    'Antonia',
    'Elena',
    'Helena',
    'Paulina',
    'Eva',
    'Magdalena',
    'Jana',
    'Elli / Elly',
    'Katharina',
    'Emely / Emelie',
    'Fiona',
    'Martha / Marta',
    'Lucy / Lucie',
    'Stella',
    'Thea',
    'Annabell / Annabelle',
    'Amy',
    'Tilda',
    'Mina',
    'Elina',
    'Jasmin / Yasmin',
    'Carla / Karla',
    'Annika',
    'Alessia',
    'Jule',
    'Rosalie',
    'Malia',
    'Carlotta / Karlotta',
    'Elisabeth',
    'Maila / Mayla',
    'Valentina',
    'Milena',
    'Nina',
    'Ronja',
    'Melissa',
    'Chiara / Kiara',
    'Hailey / Haylie',
    'Olivia',
    'Amelia',
    'Amalia',
    'Franziska'
];

export default firstnames;